name: Frontend CI/CD

on:
  pull_request:
    branches:
      - production
      - development
  push:
    branches:
      - production
      - development

jobs:
  build-test-deploy:
    name: Build, Test & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Create env file for tests
        run: |
          echo "VITE_API_URL=${{ secrets.API_URL_DEV }}" > .env

      - name: Run Playwright tests
        run: npm run test

      - name: Create env file for build
        run: |
          if [ "${GITHUB_REF_NAME}" = "development" ]; then
            echo "VITE_API_URL=${{ secrets.API_URL_DEV }}" > .env
          else
            echo "VITE_API_URL=${{ secrets.API_URL_PROD }}" > .env
          fi

      - name: Build app
        run: npm run build

      # DEPLOY TO FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ github.ref_name == 'development' && 'qsodev/' || 'qso/' }}